cart/urls.py
from django.urls import path
from .views import add_to_cart,cart_view
name = 'cart'

urlpatterns = [
    path('cart/', cart_view, name='index'),
    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),
]

my_shop_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import about_us,orders,cart,products,contacts
from django.urls import path

import register.views
import subscription.views
from about_us.views import aboutUs
from cart.views import cart_view
from my_shop_project import settings
from orders.views import checkout,order_success
from products.views import product_detail, products_by_category, category_list,add_product
from contacts.views import index
from subscription import views
from register import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),  # Admin URL
    path('', aboutUs, name='about_us'),  # Home page

    path('about-us/', include(('about_us.urls', 'about_us_app'), namespace='about_us')),

    path('cart/', include(('cart.urls', 'cart_app'), namespace='cart')),# Cart page
    path('cart/', cart_view, name='cart_view'),
    path('order/', include('orders.urls')),
    path('order-success/', order_success, name='order_success'),


    path('order/', include(('orders.urls', 'orders_app'), namespace='orders')),# Orders page

    path('categories/', include(('products.urls', 'products_app'), namespace='products')),

    path('subscription/', include(('subscription.urls', 'subscription_app'), namespace='subscription')),

    path('product/', include(('products.urls', 'product_app'), namespace='product')),

    path('category/<int:category_id>/', products_by_category, name='products_by_category'),

    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('product/<int:product_id>/<int:cart_id>', add_product, name='add_product'),

    path('subscription/', subscription.views.subscribe, name='subscription'),

    path('register/', register.views.register, name='register'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Страница логина
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('checkout/', include(('orders.urls', 'order_app'), namespace='checkout')),

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import checkout, order_checkout, order_success, payment_view,payment_succeed
app_name = 'orders'
app_name ='order_success'
urlpatterns = [
    path('checkout/', checkout, name='checkout'),  # Checkout page
    path('success/<int:order_id>/', order_success, name='order_success'),  # Order success with order_id
    path('order/checkout/', order_checkout, name='order_checkout'),
    path('payment/', payment_view, name='payment'),
    path('payment-succeed/', payment_succeed, name='payment-succeed'),
]

products/urls.py
from django.urls import path
from .views import category_list,product_detail,products_by_category, add_product
from cart.views import cart_view

app_name = 'products'

urlpatterns = [
    path('products/', category_list, name='category_list'),
    path('products/<int:category_id>/', products_by_category, name='product_list'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('add-to-cart/<int:product_id>/', add_product, name='add_to_cart'),
    path('cart/', cart_view, name='cart_view'),
    # Новый маршрут для деталей продукта
]

products/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    photo =models.ImageField(upload_to="category")
    name = models.CharField(max_length=50)
    sort = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Category'
        ordering = ['sort']

class Sale(models.Model):
    name = models.CharField(max_length=50)  # the name of sale
    discount = models.DecimalField(max_digits=5, decimal_places=2)  # percent of sale
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'{self.name} - {self.discount}; {self.start_date} - {self.end_date}'

class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    price = models.PositiveIntegerField()
    photo = models.ImageField(upload_to='product_photos')
    description = models.TextField()
    is_visible = models.BooleanField(default=True)
    sales = models.ManyToManyField(Sale, blank=True)
    stock = models.IntegerField(default=0)# list of discounts for product

    def final_price(self):
        active_sales = self.sales.filter(start_date__lte=timezone.now(), end_date__gte=timezone.now())
        if active_sales.exists():
            max_discount = max(sale.discount for sale in active_sales)
            final_price = self.price * (1 - max_discount / 100)
            return final_price
        return self.price

    class Meta:
        verbose_name_plural = 'Products'
        verbose_name = 'Product'


    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, get_object_or_404, redirect,reverse
from .models import Category, Product
from cart.models import Cart,CartItem
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.db.models import Sum



def category_list(request):
    categories = Category.objects.all()
    categories_with_count = []
    for category in categories:
        product_count = Product.objects.filter(category=category).count()
        categories_with_count.append({
            'category': category,
            'product_count': product_count,
        })
    return render(request, 'category.html', {'categories_with_count': categories_with_count})

def products_by_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    products = Product.objects.filter(category=category, is_visible=True)
    return render(request, 'product.html', {'products': products})

def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'product_detail.html', {'product': product})


# views.py

def categories_view(request):
    # Получаем категории с количеством продуктов
    categories_with_count = Category.objects.annotate(product_count=Count('products'))

    return render(request, 'category.html', {
        'categories_with_count': categories_with_count,
    })


def category_home(request):
    # Получаем первые 5 категорий
    categories = Category.objects.all()[:5]
    return render(request, 'category_home.html', {'categories': categories})

@login_required
def add_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    # Получение или создание корзины для текущего пользователя
    cart, created = Cart.objects.get_or_create(user=request.user)

    # Получение или создание элемента корзины для данного товара
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

    # Увеличение количества, если товар уже был в корзине
    cart_item.quantity += 1
    cart_item.save()

    # Перенаправление на страницу корзины после добавления товара
    return redirect('cart_view')

products/templates/category.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
    <!-- Category-->

    <link rel="stylesheet" href="{% static 'CSS/category.css' %}">
    <section class="ezy__epcategory5_ayqDrKgT">
        <div class="container">
    <div class="row">
      <div class="col">
        <h2 class="ezy__epcategory5_ayqDrKgT-heading">Product Category</h2>
      </div>
    </div>
    <div class="row mt-4 mt-sm-5 ezy__epcategory5_ayqDrKgT-row">




        <!-- card start -->
            {% for item in categories_with_count %}
          <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2 p-2">
            <a href="{% url 'products_by_category' category_id=item.category.id %}">
              <div class="card ezy__epcategory5_ayqDrKgT-card">
                <img
                  src="{{ item.category.photo.url }}"
                  class="card-img-top"
                  alt='{{ item.category.name }}'
                />
                <div class="card-body text-start pb-0">
                  <h5 class="ezy__epcategory5_ayqDrKgT-card-title m-0">{{ item.category.name }}</h5>
                  <p class="ezy__epcategory5_ayqDrKgT-card-text">avalibale {{ item.product_count  }} items</p>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
        <!-- card end -->

    </div>
  </div>
    </section>
    <!-- Category-->

    {% endblock %}

products/templates/category_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="text-center my-4">Top Categories</h1>
        <div class="row">
            {% for category in categories %}
                <div class="col-md-3 my-3">
                    <div class="card">
                        <img src="{{ category.image.url }}" class="card-img-top" alt="{{ category.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ category.name }}</h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

products/templates/product.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
        <link rel="stylesheet" href="{% static 'CSS/category.css' %}">

    <!-- Products by Category -->
       <section class="ezy__epgrid1">
          <div class="container">
            <h2 class="ezy__epgrid1-heading text-center">Our Products</h2>
            <!-- row start -->
            <div class="row ezy__epgrid1-row text-center justify-content-xl-center mt-5">
              <!-- card start -->
                {% for product in products %}
                  <div class="col-md-6 col-lg-4 col-xl-3 px-2 my-2">
                    <div class="card ezy__epgrid1-card position-relative p-2">
                      <a href="{% url 'product_detail' product.id %}">
                        <div class="ezy__epgrid1-fav-icon"><i class="fas fa-heart"></i></div>
                      </a>
                      <div class="card-body">
                        <div class="ezy__epgrid1-card-img d-flex justify-content-center align-items-center h-100 px-4">
                          <a href="{% url 'product_detail' product.id %}">
                            <img src="{{ product.photo.url }}" alt="{{ product.name }}" />
                          </a>
                        </div>
                      </div>
                      <div class="card-body h-100 pt-0 text-start">
                        <a href="{% url 'product_detail' product.id %}">
                          <h5 class="ezy__epgrid1-title">Full Body Massage Chair weightless Bluetooth</h5>
                        </a>
                        <h5 class="ezy__epgrid1-price my-2">$1725.00</h5>
                        <div class="ezy__epgrid1-details d-flex justify-content-between align-items-center">
                          <h5 class="ezy__epgrid1-ratings"><i class="fas fa-star me-1"></i>4.6</h5>
                          <a href="{% url 'product_detail' product.id %}">
                            <h5 class="ezy__epgrid1-cart"><i class="fas fa-shopping-cart"></i></h5>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              <!-- card end -->

    <!-- Products by Category -->

{% endblock %}

products/templates/product_detail.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'CSS/product_detail.css' %}">
<section class="ezy__epoverview4_0ti4wMLR" id="ezy__epoverview4_0ti4wMLR">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="ezy__epoverview4_0ti4wMLR-card p-3 p-sm-4 p-lg-5 me-lg-4">
          <div class="text-center mb-3 p-md-4">
            <img
              <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="img-fluid w-100" />
          </div>

          <ul class="nav ezy__epoverview4_0ti4wMLR-gallery">
            {% for image in product.photo.all %}

              <li>
                <img
                  src="{{ image.url }}"  <!-- Галерея изображений -->
                  alt="{{ product.name }}"
                  class="img-fluid"
                />
              </li>
            </a>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col-lg-6 mt-4">
        <div class="mb-4 pb-lg-2">
          <h1 class="ezy__epoverview4_0ti4wMLR-heading mb-3">{{product.name}}</h1>
          <p class="ezy__epoverview4_0ti4wMLR-content mb-4">
            <span>4.7</span> <i class="fas fa-star mx-2"></i>
            <span class="ms-2">87 Order</span>
          </p>
          <div class="row my-4">
            <div class="col-12 col-lg-10 col-xl-8">
              <p class="ezy__epoverview4_0ti4wMLR-content mb-0">
               {{product.description}}
              </p>
            </div>
          </div>
          <h3 class="ezy__epoverview4_0ti4wMLR-price fw-bold mb-0">brand</h3>
        </div>

        <form action="#!">
          <div class="mb-4">
            <h5 class="ezy__epoverview4_0ti4wMLR-title mb-2">Color</h5>
            <div
              class="btn-group ezy__epoverview4_0ti4wMLR-radios d-block mb-2"
              role="group"
              aria-label="Basic radio toggle button group"
            >
              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-color"
                id="ezy__epoverview4_0ti4wMLR-color1"
                autocomplete="off"
                checked
              />
              <label
                class="btn me-1 mt-1"
                style="--ezy-product-color: #ffc107"
                for="ezy__epoverview4_0ti4wMLR-color1"
              ></label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-color"
                id="ezy__epoverview4_0ti4wMLR-color2"
                autocomplete="off"
              />
              <label
                class="btn me-1 mt-1"
                style="--ezy-product-color: #3aa9f3"
                for="ezy__epoverview4_0ti4wMLR-color2"
              ></label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-color"
                id="ezy__epoverview4_0ti4wMLR-color3"
                autocomplete="off"
              />
              <label
                class="btn me-1 mt-1"
                style="--ezy-product-color: #ff7171"
                for="ezy__epoverview4_0ti4wMLR-color3"
              ></label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-color"
                id="ezy__epoverview4_0ti4wMLR-color4"
                autocomplete="off"
              />
              <label
                class="btn me-1 mt-1"
                style="--ezy-product-color: #161d25"
                for="ezy__epoverview4_0ti4wMLR-color4"
              ></label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-color"
                id="ezy__epoverview4_0ti4wMLR-color5"
                autocomplete="off"
              />
              <label
                class="btn me-1 mt-1"
                style="--ezy-product-color: #ff0000"
                for="ezy__epoverview4_0ti4wMLR-color5"
              ></label>
            </div>
          </div>
          <div class="mb-4">
            <h5 class="ezy__epoverview4_0ti4wMLR-title mb-0">Size: <span class="opacity-50">Extra Extra Small</span></h5>
            <div
              class="btn-group ezy__epoverview4_0ti4wMLR-radios d-block mb-2"
              role="group"
              aria-label="Basic radio toggle button group"
            >
              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size1"
                autocomplete="off"
                checked
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size1">
                XXS
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size2"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size2">
                XS
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size3"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size3">
                S
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size4"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size4">
                M
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size5"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size5">
                L
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size6"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size6">
                XL
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size7"
                autocomplete="off"
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size7">
                XXL
              </label>

              <input
                type="radio"
                class="btn-check"
                name="ezy__epoverview4_0ti4wMLR-size"
                id="ezy__epoverview4_0ti4wMLR-size8"
                autocomplete="off"
                disabled
              />
              <label class="btn me-2 mt-2 rounded-pill overflow-hidden px-3 py-1" for="ezy__epoverview4_0ti4wMLR-size8">
                XXXL
              </label>
            </div>
          </div>
          <div class="mb-4">
            <h5 class="ezy__epoverview4_0ti4wMLR-title mb-2">QTY</h5>
            <div class="input-group ezy__epoverview4_0ti4wMLR-qty d-inline-flex mb-2">
              <input
                type="text"
                class="form-control"
                placeholder=""
                value="1"
                aria-label="Example text with button addon"
                aria-describedby="button-addon1"
              />
              <div class="input-group-text d-flex flex-column bg-transparent p-0">
                <button class="btn" type="button">-</button>
                <button class="btn" type="button">+</button>
              </div>
            </div>
          </div>
          <script>
            document.getElementById('incrementBtn').addEventListener('click', function() {
              var input = document.getElementById('quantityInput');
              input.value = parseInt(input.value) + 1;
            });

            document.getElementById('decrementBtn').addEventListener('click', function() {
              var input = document.getElementById('quantityInput');
              if (parseInt(input.value) > 1) {
                input.value = parseInt(input.value) - 1;
              }
            });
          </script>

          <div class="row align-items-center">
    <div class="col-md-10 d-flex">
        <!-- Кнопка для покупки -->
        <button
                class="btn ezy__epoverview4_0ti4wMLR-btn text-uppercase d-inline-flex justify-content-center align-items-center px-3 px-sm-5 me-2 me-lg-3 w-100"
                onclick="location.href='{% url 'orders:checkout' %}'"
              >
                Buy Now
              </button>

              <!-- Кнопка для добавления в корзину -->
              {% if user.is_authenticated %}
                <form method="POST" href="{% url 'product:add_to_cart' product.id %}">
                    {% csrf_token %}

                    <a href="{% url 'product:add_to_cart' product.id %}"
                      <h5 class="ezy__epoverview4_0ti4wMLR-btn-outline text-uppercase bg-transparent d-inline-flex justify-content-center align-items-center px-3 px-sm-4 w-100">Add to Cart</h5>
                    </a>
                </form>
            {% else %}
                <a href="{% url 'register:login' %}" class="btn ezy__epoverview4_0ti4wMLR-btn-outline text-uppercase bg-transparent d-inline-flex justify-content-center align-items-center px-3 px-sm-4 w-100">
                    Log In to Add to Cart
                </a>
            {% endif %}
            </div>


    <div class="col-12 mt-3">
        <!-- Можно добавить дополнительный контент или элементы -->
    </div>
</div>



            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}