cart/urls.py
from django.urls import path
from .views import add_to_cart,cart_view
name = 'cart'

urlpatterns = [
    path('cart/', cart_view, name='index'),
    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),
]

my_shop_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import about_us,orders,cart,products,contacts
from django.urls import path

import register.views
import subscription.views
from about_us.views import aboutUs
from cart.views import cart_view
from my_shop_project import settings
from orders.views import checkout,order_success
from products.views import product_detail, products_by_category, category_list,add_product
from contacts.views import index
from subscription import views
from register import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),  # Admin URL
    path('', aboutUs, name='about_us'),  # Home page

    path('about-us/', include(('about_us.urls', 'about_us_app'), namespace='about_us')),

    path('cart/', include(('cart.urls', 'cart_app'), namespace='cart')),# Cart page
    path('cart/', cart_view, name='cart_view'),
    path('order/', include('orders.urls')),
    path('order-success/', order_success, name='order_success'),


    path('order/', include(('orders.urls', 'orders_app'), namespace='orders')),# Orders page

    path('categories/', include(('products.urls', 'products_app'), namespace='products')),

    path('subscription/', include(('subscription.urls', 'subscription_app'), namespace='subscription')),

    path('product/', include(('products.urls', 'product_app'), namespace='product')),

    path('category/<int:category_id>/', products_by_category, name='products_by_category'),

    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('product/<int:product_id>/<int:cart_id>', add_product, name='add_product'),

    path('subscription/', subscription.views.subscribe, name='subscription'),

    path('register/', register.views.register, name='register'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Страница логина
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('checkout/', include(('orders.urls', 'order_app'), namespace='checkout')),

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import checkout, order_checkout, order_success, payment_view,payment_succeed
app_name = 'orders'
app_name ='order_success'
urlpatterns = [
    path('checkout/', checkout, name='checkout'),  # Checkout page
    path('success/<int:order_id>/', order_success, name='order_success'),  # Order success with order_id
    path('order/checkout/', order_checkout, name='order_checkout'),
    path('payment/', payment_view, name='payment'),
    path('payment-succeed/', payment_succeed, name='payment-succeed'),
]

products/urls.py
from django.urls import path
from .views import category_list,product_detail,products_by_category, add_product
from cart.views import cart_view

app_name = 'products'

urlpatterns = [
    path('products/', category_list, name='category_list'),
    path('products/<int:category_id>/', products_by_category, name='product_list'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('add-to-cart/<int:product_id>/', add_product, name='add_to_cart'),
    path('cart/', cart_view, name='cart_view'),
    # Новый маршрут для деталей продукта
]

templates/footer.html
{% load static %}
<!-- Footer -->
    <link rel="stylesheet" href="{% static 'CSS/footer.css' %}">
    <footer class="ezy__footer18_j6U7vf7S">
      <div class="container">
        <div class="row text-center text-sm-start mb-md-5">
          <div class="col-lg-3">
            <h2 class="fw-bold">MyShopStyle</h2>
            <p class="ezy__footer18_j6U7vf7S-text opacity-75 mt-4 pe-lg-4">
              Be the first to find out about exclusive deals, the latest Lookbooks trends. We're on a mission to build a
              better future where technology.
            </p>
          </div>
          <div class="col-sm-6 col-lg-2 mt-4 mt-lg-0">
            <h5>Quick Links</h5>
            <ul class="nav flex-column ezy__footer18_j6U7vf7S-quick-links">
              <li>
                <a href="{% url 'about_us' %}"> Home</a>
              </li>
              <li>
                <a href="{% url  'products:category_list' %}"> Products</a>
              </li>
              <li>
                <a href="#!"> Services</a>
              </li>
            </ul>
          </div>
          <div class="col-sm-6 col-lg-2 mt-4 mt-lg-0">
            <h5>Social Media</h5>
            <ul class="nav flex-column ezy__footer18_j6U7vf7S-quick-links">
              <li>
                <a href="#!"> Facebook</a>
              </li>
              <li>
                <a href="#!"> Instagram</a>
              </li>
              <li>
                <a href="#!"> LinkedIn</a>
              </li>
              <li>
                <a href="#!"> Twitter</a>
              </li>
            </ul>
          </div>
          <div class="col-sm-6 col-lg-2 mt-4 mt-lg-0">
            <h5>Job Info</h5>
            <ul class="nav flex-column ezy__footer18_j6U7vf7S-quick-links">
              <li>
                <a href="#!"> Select</a>
              </li>
              <li>
                <a href="#!"> Service</a>
              </li>
              <li>
                <a href="#!"> Payment</a>
              </li>
            </ul>
          </div>
          <div class="col-sm-6 col-lg-3 mt-4 mt-lg-0">
            <h5>Contact Us</h5>
            <ul class="nav flex-column ezy__footer18_j6U7vf7S-quick-links">
              <li>Sylhet, Bangladesh</li>
              <li>
                <a href="#!"><span class="fas fa-envelope me-2 small opacity-50"></span> contact@myshopstyle.com</a>
              </li>
              <li>
                <a href="#!"><span class="fas fa-phone me-2 small opacity-50"></span> +880 1633-154215</a>
              </li>
            </ul>
          </div>
        </div>
        <hr />
        <div class="row d-flex justify-content-between align-items-center text-center text-lg-start">
          <div class="col-md-6">
            <p class="mb-0 mt-1 opacity-75">Copyright &copy; Easy Frontend, All rights reserved</p>
          </div>
          <div class="col-md-6">
            <ul class="ezy__footer18_j6U7vf7S-nav nav justify-content-center justify-content-md-end mt-1">
              <li class="nav-item opacity-75">
                <a class="nav-link" href="#!">Privacy</a>
              </li>
              <li class="nav-item opacity-75">
                <a class="nav-link" href="#!">Security</a>
              </li>
              <li class="nav-item opacity-75">
                <a class="nav-link" href="#!">Terms</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
<!-- Footer -->

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ShopStyle - Shop Website Template</title>

    <!-- Подключение Bootstrap через CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    
    <!-- Nav Bar -->
    {% include 'navbar.html' %}
    <!-- Nav Bar -->
    
    
    {% block content %}
    
        
    {% endblock %}
    
    
    <!-- Footer -->
    {% include 'footer.html' %}
    <!-- Footer -->

</body>
</html>

templates/navbar.html
{% load static %}
<!-- Nav Bar -->
    <link rel="stylesheet" href="{% static 'CSS/navbar.css' %}">
    <div class="ezy__nav2">
        <nav class="navbar navbar-expand-lg  py-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'about_us:index' %}">
                    My Shop Project
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span>
                        <span></span>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 mt-4 mt-lg-0">
                        <li class="nav-item"><a class="nav-link active" href="{% url 'about_us:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'products:category_list' %}">Products</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cart:index' %}">Cart</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'orders:checkout' %}">Orders</a></li>
                    </ul>
                    <ul class="navbar-nav flex-row mb-2 mb-lg-0 ms-lg-3">
                        <li class="nav-item me-2">
                            <!-- Кнопка Sign Up, ведущая на страницу регистрации -->
                            <a href="{% url 'register' %}" class="btn btn-outline-primary px-3">Sign Up</a>
                        </li>
                        
                        <li class="nav-item me-2">
                            <!-- Кнопка Log Out, ведущая на URL выхода из системы -->
                            <a href="{% url 'register:logout' %}" class="btn btn-outline-primary px-3">Log Out</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </div>
    <!-- Nav Bar -->