about_us/urls.py
from django.urls import path
from .views import aboutUs
from django.urls import path
from django.contrib.auth import views as auth_views


name = 'about_us'

urlpatterns = [
    path('', aboutUs, name='index'),
]

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart_view
name = 'cart'

urlpatterns = [
    path('cart/', cart_view, name='index'),
    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),
]

my_shop_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import about_us,orders,cart,products,contacts
from django.urls import path

import register.views
import subscription.views
from about_us.views import aboutUs
from cart.views import cart_view
from my_shop_project import settings
from orders.views import checkout,order_success
from products.views import product_detail, products_by_category, category_list,add_product
from contacts.views import index
from subscription import views
from register import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),  # Admin URL
    path('', aboutUs, name='about_us'),  # Home page

    path('about-us/', include(('about_us.urls', 'about_us_app'), namespace='about_us')),

    path('cart/', include(('cart.urls', 'cart_app'), namespace='cart')),# Cart page
    path('cart/', cart_view, name='cart_view'),
    path('order/', include('orders.urls')),
    path('order-success/', order_success, name='order_success'),


    path('order/', include(('orders.urls', 'orders_app'), namespace='orders')),# Orders page

    path('categories/', include(('products.urls', 'products_app'), namespace='products')),

    path('subscription/', include(('subscription.urls', 'subscription_app'), namespace='subscription')),

    path('product/', include(('products.urls', 'product_app'), namespace='product')),

    path('category/<int:category_id>/', products_by_category, name='products_by_category'),

    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('product/<int:product_id>/<int:cart_id>', add_product, name='add_product'),

    path('subscription/', subscription.views.subscribe, name='subscription'),

    path('register/', register.views.register, name='register'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Страница логина
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('checkout/', include(('orders.urls', 'order_app'), namespace='checkout')),

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import category_list,product_detail,products_by_category, add_product
from cart.views import cart_view

app_name = 'products'

urlpatterns = [
    path('products/', category_list, name='category_list'),
    path('products/<int:category_id>/', products_by_category, name='product_list'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('add-to-cart/<int:product_id>/', add_product, name='add_to_cart'),
    path('cart/', cart_view, name='cart_view'),
    # Новый маршрут для деталей продукта
]

subscription/urls.py
from django.urls import path
from .views import subscribe
name = 'subscribe'

urlpatterns = [
    path('subscription/', subscribe, name='subscribe'),
]

about_us/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def aboutUs(request):
    return render(request, 'about_us/aboutus.html')

about_us/templates/about_us/aboutus.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

        <!-- Header -->
        <link rel="stylesheet" href="{% static 'CSS/header.css' %}">
        <header class="masthead text-center text-white">
                    <div class="masthead-content">
                        <div class="container px-5">
                            <h1 class="masthead-heading mb-0">Shopping As Lifestyle</h1>
                            <h2 class="masthead-subheading mb-0">Look Like You Feel</h2>
                            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'products:category_list' %}">Start Shop</a>
                        </div>
                    </div>
                    <div class="bg-circle-1 bg-circle"></div>
                    <div class="bg-circle-2 bg-circle"></div>
                    <div class="bg-circle-3 bg-circle"></div>
                    <div class="bg-circle-4 bg-circle"></div>
        </header>
        <!-- Header -->



        <!-- About Us -->
        <link rel="stylesheet" href="{% static 'CSS/about_us.css' %}">
        <section class="ezy__about12 light" id="ezy__about12">
          <div class="container">
            <div class="row justify-content-center align-items-center">
              <div class="col-12 col-lg-5 mb-5 mb-lg-0">
                <div class="">
                  <h1 class="ezy__about12-heading">ABOUT US</h1>
                  <p class="ezy__about12-sub-heading my-4">
                    Completely network collaborative web services via user-centric initiatives. Quickly promote sticky
                    testing procedures collaborator before unique process improvements. Since our inception set out in 2012,
                    TalEx has set out to disrupt inception the HR & Talent/Staffing Management industry. Purposefully
                    designed by our founders (Amrita Grewal and Julie Dacar) to connect great companies and great talent.
                  </p>
                  <div class="mt-5">
                    <a class="btn ezy__about12-btn" href="{% url 'subscription:subscribe' %}">Subscribe</a>
                      {% csrf_token %}
                  </div>
                </div>
              </div>
              <div class="col-12 col-lg-6">
                <div class="ms-lg-5">
                  <img src="https://cdn.easyfrontend.com/pictures/quiz_1.png" alt="" class="img-fluid" />
                </div>
              </div>
            </div>
          </div>

        </section>
        <!-- About Us -->

    {% endblock %}